services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assign-app
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
